namespace OKX.Net.Objects.BlockTrading;
/// <summary>
/// Represents a response for creating an RFQ on OKX.
/// </summary>
public record OKXCreateRFQResponse(
    [property: JsonPropertyName("cTime"), JsonConverter(typeof(DateTimeConverter))]
    DateTime CreationTime, // The timestamp the RFQ was created. Unix timestamp format in milliseconds.

    [property: JsonPropertyName("uTime"), JsonConverter(typeof(DateTimeConverter))]
    DateTime LastUpdatedTime, // The timestamp the RFQ was last updated. Unix timestamp format in milliseconds.

    [property: JsonPropertyName("state")]
    RFQStatus Status, // The status of the RFQ. Valid values can be active, canceled, pending_fill, filled, expired, traded_away, failed.

    [property: JsonPropertyName("counterparties")]
    List<string> Counterparties, // The list of counterparties traderCode the RFQ was broadcast to.

    [property: JsonPropertyName("validUntil"), JsonConverter(typeof(DateTimeConverter))]
    DateTime ExpiryTime, // The timestamp the RFQ expires. Unix timestamp format in milliseconds.

    [property: JsonPropertyName("clRfqId")]
    string ClientRfqId, // Client-supplied RFQ ID. Treated as client sensitive information.

    [property: JsonPropertyName("tag")]
    string Tag, // RFQ tag. The block trade associated with the RFQ will have the same tag.

    [property: JsonPropertyName("allowPartialExecution")]
    bool AllowPartialExecution, // Whether the RFQ can be partially filled provided that the shape of legs stays the same.

    [property: JsonPropertyName("traderCode")]
    string TakerTraderCode, // A unique identifier of the taker.

    [property: JsonPropertyName("rfqId")]
    string RfqId, // The unique identifier of the RFQ generated by the system.

    [property: JsonPropertyName("legs")]
    List<OKXCreateQuoteLeg> Legs // An array of objects containing each leg of the RFQ.
);
